name: pyauto

# Controls when the action will run. 
on:
  push:
    paths:
    - '**.py'
  schedule:
    - cron: '0 14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.2

      - name: Run a multi-line script
        run: pip install selenium
        

      - name: Run app
        run: python pyauto.py
        env:
         JD_COOKIE: ${{ secrets.JD_COOKIE }}
         JD_COOKIE_2: ${{ secrets.JD_COOKIE_2 }} 
         PUSH_KEY: ${{ secrets.PUSH_KEY }}
